version: '3'
services:
  web:
    image: nginx:1.18.0
    ports:
      - 8000:80
    depends_on:
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
     - ./.env
    ports:
      - "3308:3308"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
